Analysing Real world Weather Data

In [2]:
import pandas as pd
import os
os.getcwd()

'C:\\Users\\MY PC\\Desktop\\DATA SCIENCE\\real_world_project'

In [3]:
data=pd.read_csv('C:\\Users\\MY PC\Desktop\\DATA SCIENCE\\real_world_project\\POWER_Point_Hourly_20010101_20210331_027d4709N_077d6887E_LST (2).csv')

In [5]:
data

,YEAR,MO,DY,HR,CLRSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
0,2001,1,1,0,0.0,-999.0,0.0,12.78,4.84,8.81,5.43,58.38,0.01,99.10,2.46,201.60,5.44,201.40
1,2001,1,1,1,0.0,-999.0,0.0,12.35,4.96,8.65,5.49,60.50,0.01,99.06,2.23,208.45,4.44,208.37
2,2001,1,1,2,0.0,-999.0,0.0,11.97,5.07,8.51,5.49,62.50,0.01,99.04,1.98,209.60,3.49,209.67
3,2001,1,1,3,0.0,-999.0,0.0,12.01,5.15,8.58,5.55,62.69,0.01,99.02,1.57,198.89,2.54,198.99
4,2001,1,1,4,0.0,-999.0,0.0,11.95,5.33,8.64,5.62,63.69,0.02,99.03,1.36,175.70,2.15,175.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177475,2021,3,31,19,0.0,-999.0,0.0,27.34,-10.60,8.37,1.59,7.00,0.00,98.05,4.57,322.15,10.26,322.18
177476,2021,3,31,20,0.0,-999.0,0.0,25.94,-10.74,7.59,1.59,7.50,0.00,98.10,4.46,323.83,10.00,323.86
177477,2021,3,31,21,0.0,-999.0,0.0,24.52,-10.95,6.79,1.59,8.06,0.00,98.13,4.35,325.68,9.74,325.75
177478,2021,3,31,22,0.0,-999.0,0.0,23.26,-11.30,5.98,1.53,8.44,0.00,98.14,4.38,326.71,9.72,326.81
177479,2021,3,31,23,0.0,-999.0,0.0,22.14,-11.71,5.21,1.46,8.69,0.00,98.14,4.53,327.24,9.77,327.34

In [8]:
data.rename(columns={'DY':'DAY','HR':'HOURS'})

,YEAR,MO,DAY,HOURS,CLRSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
0,2001,1,1,0,0.0,-999.0,0.0,12.78,4.84,8.81,5.43,58.38,0.01,99.10,2.46,201.60,5.44,201.40
1,2001,1,1,1,0.0,-999.0,0.0,12.35,4.96,8.65,5.49,60.50,0.01,99.06,2.23,208.45,4.44,208.37
2,2001,1,1,2,0.0,-999.0,0.0,11.97,5.07,8.51,5.49,62.50,0.01,99.04,1.98,209.60,3.49,209.67
3,2001,1,1,3,0.0,-999.0,0.0,12.01,5.15,8.58,5.55,62.69,0.01,99.02,1.57,198.89,2.54,198.99
4,2001,1,1,4,0.0,-999.0,0.0,11.95,5.33,8.64,5.62,63.69,0.02,99.03,1.36,175.70,2.15,175.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177475,2021,3,31,19,0.0,-999.0,0.0,27.34,-10.60,8.37,1.59,7.00,0.00,98.05,4.57,322.15,10.26,322.18
177476,2021,3,31,20,0.0,-999.0,0.0,25.94,-10.74,7.59,1.59,7.50,0.00,98.10,4.46,323.83,10.00,323.86
177477,2021,3,31,21,0.0,-999.0,0.0,24.52,-10.95,6.79,1.59,8.06,0.00,98.13,4.35,325.68,9.74,325.75
177478,2021,3,31,22,0.0,-999.0,0.0,23.26,-11.30,5.98,1.53,8.44,0.00,98.14,4.38,326.71,9.72,326.81
177479,2021,3,31,23,0.0,-999.0,0.0,22.14,-11.71,5.21,1.46,8.69,0.00,98.14,4.53,327.24,9.77,327.34

In [13]:
data['CLRSKY_SFC_SW_DWN'].isnull().sum()

0

In [14]:
data.WS10M.mean()

2.878919990984957

In [15]:
data.WS50M.mean()

4.319224419653002

In [16]:
data.PS.mean()

98.66995762902836

In [17]:
data.PS.std()

0.712395277716507

In [18]:
data.RH2M.var()

577.6611872536097

In [19]:
data.QV2M.var()

37.29774357108447

In [22]:
data.YEAR.value_counts()

2020    8784
2004    8784
2008    8784
2016    8784
2012    8784
2001    8760
2013    8760
2019    8760
2018    8760
2017    8760
2015    8760
2014    8760
2011    8760
2002    8760
2010    8760
2009    8760
2007    8760
2006    8760
2005    8760
2003    8760
2021    2160
Name: YEAR, dtype: int64

In [23]:
data.YEAR==2021]

0         False
1         False
2         False
3         False
4         False
          ...
177475     True
177476     True
177477     True
177478     True
177479     True
Name: YEAR, Length: 177480, dtype: bool

In [28]:
data.ALLSKY_SFC_UV_INDEX.

dtype('float64')

In [30]:
data.groupby('YEAR').mean()

,MO,DY,HR,CLRSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
YEAR,,,,,,,,,,,,,,,,,
2001,6.526027,15.720548,11.5,237.044903,-482.014538,0.061247,27.144046,7.273535,17.208836,8.441763,33.751549,0.041410,98.603515,2.907462,225.728287,4.279900,226.633615
2002,6.526027,15.720548,11.5,233.816611,-481.900785,0.634255,27.464331,7.929106,17.696811,8.140041,35.375630,0.048817,98.621910,2.945336,210.311465,4.347425,210.862378
2003,6.526027,15.720548,11.5,232.177866,-481.689055,-0.012549,26.080951,9.828960,17.954960,9.497936,44.186576,0.069138,98.682796,2.695256,201.501748,4.056098,202.277711
2004,6.513661,15.756831,11.5,234.344727,-482.065907,-0.507934,26.837029,9.999550,18.418324,9.300855,41.562204,0.063923,98.655091,3.046434,214.152484,4.543601,215.066107
2005,6.526027,15.720548,11.5,238.446216,-481.900788,0.062082,26.319597,9.392575,17.856115,9.078958,41.296006,0.055413,98.662474,3.077463,216.023223,4.651654,216.414092
2006,6.526027,15.720548,11.5,235.607920,-481.901395,0.295525,27.235103,9.868712,18.551910,9.449555,39.634737,0.052171,98.647716,3.199485,212.888917,4.785924,213.603578
2007,6.526027,15.720548,11.5,233.963838,-481.676900,-2.109047,26.637708,10.097360,18.367537,9.485703,41.324900,0.060478,98.633483,3.086461,211.427405,4.631468,212.211518
2008,6.513661,15.756831,11.5,230.164146,-481.847802,-2.271226,25.894167,10.516341,18.205237,10.327744,45.855693,0.075416,98.629816,2.758032,212.650721,4.203656,213.596544
2009,6.526027,15.720548,11.5,235.380458,-481.786061,-1.403127,27.158986,9.865924,18.512459,9.162007,40.359417,0.058282,98.630963,2.919764,215.757233,4.368446,216.999613
2010,6.526027,15.720548,11.5,230.533939,-481.915934,-0.479338,26.798382,10.911916,18.855127,9.932287,45.863008,0.066820,98.625046,2.817943,201.640829,4.190201,202.287546
2011,6.526027,15.720548,11.5,231.788358,-481.679453,-1.110317,25.692618,11.864510,18.778514,10.496474,48.941387,0.073441,98.617626,2.677772,206.419564,3.994701,207.172775
2012,6.513661,15.756831,11.5,232.025954,-481.844469,0.220180,25.617075,9.199970,17.408472,9.093391,42.985295,0.082160,98.607437,3.084283,239.303085,4.675528,239.662964
2013,6.526027,15.720548,11.5,234.839759,-481.794543,-0.421671,24.962200,12.018590,18.490465,10.657857,52.278215,0.120130,98.666465,2.830129,213.581878,4.289868,214.462462
2014,6.526027,15.720548,11.5,232.859707,-482.023590,0.597491,26.103913,10.070281,18.087128,9.083220,42.185699,0.060249,98.739495,2.837772,223.773356,4.217525,224.052273
2015,6.526027,15.720548,11.5,232.955515,-481.679360,0.665654,26.127977,10.579397,18.353715,9.303642,42.609675,0.066604,98.789205,2.739277,215.043567,4.088211,215.734092
2016,6.513661,15.756831,11.5,228.396553,-481.846111,0.586473,26.719775,9.607585,18.163649,9.614501,41.090319,0.087427,98.676201,2.624433,209.890442,3.982654,210.507141
2017,6.526027,15.720548,11.5,232.627030,-481.796912,-1.883734,26.708637,9.590239,18.149476,9.132119,39.792447,0.058041,98.672659,2.927717,222.332425,4.426075,222.453668
2018,6.526027,15.720548,11.5,228.178721,-482.030897,-4.833543,26.105764,10.526194,18.316073,10.003901,45.422529,0.093024,98.650551,2.773437,211.329107,4.183854,212.120121
2019,6.526027,15.720548,11.5,226.277647,-481.812813,-0.551358,25.971337,11.959816,18.965614,10.345123,48.701031,0.072046,98.739610,2.799747,207.071662,4.176208,207.561259
2020,6.513661,15.756831,11.5,230.814958,-481.846787,-2.932024,25.967631,11.546664,18.757095,10.039673,45.662214,0.054962,98.720386,2.858295,210.152824,4.271607,210.910856
2021,2.000000,15.533333,11.5,197.081542,-522.380653,-3.172569,20.207542,2.560181,11.384023,4.840500,36.708028,0.017574,99.184509,2.765227,202.567699,4.398972,203.234255

In [31]:
data.groupby('YEAR').min()

,MO,DY,HR,CLRSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
YEAR,,,,,,,,,,,,,,,,,
2001,1,1,0,0.0,-999.0,-999.0,3.71,-16.49,-4.05,0.92,3.62,0.0,97.16,0.02,0.0,0.02,0.00
2002,1,1,0,0.0,-999.0,-999.0,2.44,-15.05,-4.18,1.04,1.62,0.0,96.83,0.04,0.0,0.08,0.00
2003,1,1,0,0.0,-999.0,-999.0,3.31,-14.41,-1.19,1.04,2.50,0.0,97.11,0.02,0.0,0.01,0.00
2004,1,1,0,0.0,-999.0,-999.0,4.44,-12.50,-0.66,1.34,3.50,0.0,96.98,0.08,0.0,0.06,0.00
2005,1,1,0,0.0,-999.0,-999.0,4.31,-13.00,-1.83,1.22,3.44,0.0,97.14,0.06,0.0,0.05,0.00
2006,1,1,0,0.0,-999.0,-999.0,2.32,-15.45,-4.53,0.79,1.94,0.0,96.97,0.09,0.0,0.06,0.00
2007,1,1,0,0.0,-999.0,-999.0,2.71,-13.70,-2.67,1.22,6.12,0.0,97.02,0.06,0.0,0.06,0.00
2008,1,1,0,0.0,-999.0,-999.0,2.66,-18.86,-5.63,0.67,4.00,0.0,97.07,0.02,0.0,0.02,0.00
2009,1,1,0,0.0,-999.0,-999.0,5.15,-14.27,0.29,0.98,2.69,0.0,97.12,0.00,0.0,0.01,0.00
2010,1,1,0,0.0,-999.0,-999.0,4.03,-9.88,0.03,1.71,4.19,0.0,97.15,0.02,0.0,0.04,0.00
2011,1,1,0,0.0,-999.0,-999.0,0.12,-9.08,-1.74,1.83,5.62,0.0,97.09,0.06,0.0,0.07,0.00
2012,1,1,0,0.0,-999.0,-999.0,0.99,-19.73,-4.94,0.49,2.12,0.0,96.95,0.04,0.0,0.05,0.00
2013,1,1,0,0.0,-999.0,-999.0,-0.04,-9.92,-4.55,1.71,4.38,0.0,97.21,0.03,0.0,0.03,0.00
2014,1,1,0,0.0,-999.0,-999.0,2.52,-15.21,-2.62,0.98,4.81,0.0,96.96,0.05,0.0,0.06,0.00
2015,1,1,0,0.0,-999.0,-999.0,3.37,-12.86,-2.56,1.10,1.94,0.0,97.17,0.02,0.0,0.04,0.00
2016,1,1,0,0.0,-999.0,-999.0,4.56,-14.91,-3.29,1.10,3.62,0.0,97.22,0.06,0.0,0.05,0.00
2017,1,1,0,0.0,-999.0,-999.0,2.38,-12.15,-4.69,1.40,3.50,0.0,97.30,0.07,0.0,0.11,0.00
2018,1,1,0,0.0,-999.0,-999.0,2.32,-16.53,-2.12,0.85,3.81,0.0,96.78,0.03,0.0,0.06,0.00
2019,1,1,0,0.0,-999.0,-999.0,0.63,-8.96,-1.68,1.83,5.06,0.0,97.03,0.00,0.0,0.00,0.00
2020,1,1,0,0.0,-999.0,-999.0,1.87,-14.34,-0.36,1.16,7.12,0.0,97.01,0.07,0.0,0.02,0.00
2021,1,1,0,0.0,-999.0,-999.0,2.67,-11.71,0.00,1.46,3.44,0.0,97.60,0.07,0.0,0.03,0.24

In [32]:
data.groupby('YEAR').max()

,MO,DY,HR,CLRSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
YEAR,,,,,,,,,,,,,,,,,
2001,12,31,23,1020.52,0.80,10.55,48.28,26.62,31.11,22.46,100.00,3.52,100.25,10.92,359.85,13.06,359.92
2002,12,31,23,1034.38,0.80,11.00,48.08,26.10,31.55,21.79,100.00,8.90,100.21,9.88,359.84,11.92,359.81
2003,12,31,23,1029.27,0.80,11.42,48.15,27.45,30.83,23.74,100.00,9.17,100.34,9.29,359.86,11.55,359.88
2004,12,31,23,1014.70,0.80,11.00,47.03,26.83,31.84,22.83,100.00,7.99,100.21,15.04,359.83,17.94,359.87
2005,12,31,23,1040.12,0.80,10.60,47.82,27.36,32.83,23.50,100.00,8.39,100.21,11.34,359.80,14.11,359.89
2006,12,31,23,1006.58,0.80,11.40,47.32,26.79,31.89,22.83,99.31,6.29,100.23,11.28,359.88,13.80,359.90
2007,12,31,23,1008.70,0.80,11.12,48.23,28.51,32.12,25.27,100.00,7.13,100.14,10.16,359.82,11.97,359.83
2008,12,31,23,1026.23,0.80,10.45,45.33,27.14,30.85,23.19,100.00,4.55,100.08,9.05,359.83,11.76,359.89
2009,12,31,23,1017.27,0.79,10.62,47.14,27.98,31.76,24.54,100.00,7.74,100.32,9.99,359.84,12.03,359.89
2010,12,31,23,1035.12,0.79,10.27,48.54,26.88,31.55,22.77,100.00,8.26,100.37,10.95,359.79,13.38,359.86
2011,12,31,23,1011.67,0.79,10.67,47.38,27.34,31.62,23.56,100.00,10.37,100.12,9.98,359.73,12.65,359.92
2012,12,31,23,1031.42,0.80,10.52,48.08,27.10,31.62,23.07,100.00,7.31,100.14,10.79,359.83,12.88,359.92
2013,12,31,23,1043.88,0.80,11.02,47.87,27.32,31.49,23.44,100.00,20.12,100.22,9.46,359.78,11.10,359.85
2014,12,31,23,1033.80,0.79,10.95,48.76,27.19,31.59,23.32,100.00,8.58,100.36,11.78,359.86,13.77,359.90
2015,12,31,23,1061.83,0.79,10.40,46.75,26.69,30.62,22.46,100.00,7.75,100.29,9.23,359.84,11.46,359.91
2016,12,31,23,1028.98,0.81,10.65,47.19,28.65,32.10,25.33,100.00,12.67,100.22,9.33,359.87,12.27,359.93
2017,12,31,23,1019.25,0.80,10.55,46.91,26.82,31.23,22.64,100.00,8.67,100.36,9.87,359.87,12.31,359.92
2018,12,31,23,1019.98,0.78,10.33,46.96,27.47,31.27,23.68,100.00,5.28,100.31,10.46,359.81,12.57,359.94
2019,12,31,23,1030.62,0.77,11.65,48.72,27.86,31.89,24.29,100.00,6.71,100.32,11.28,359.88,14.30,359.91
2020,12,31,23,1039.30,0.78,12.27,47.83,29.22,32.33,26.18,100.00,5.17,100.32,10.91,359.86,13.44,359.91
2021,3,31,23,1005.83,0.80,9.35,42.83,16.10,22.34,11.54,100.00,3.83,99.95,12.09,359.73,14.95,359.83

Data with temp >40 and Relative humidity>60

In [36]:
data[(data.T2M>40)|(data.RH2M>60)]

,YEAR,MO,DY,HR,CLRSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
1,2001,1,1,1,0.00,-999.00,0.00,12.35,4.96,8.65,5.49,60.50,0.01,99.06,2.23,208.45,4.44,208.37
2,2001,1,1,2,0.00,-999.00,0.00,11.97,5.07,8.51,5.49,62.50,0.01,99.04,1.98,209.60,3.49,209.67
3,2001,1,1,3,0.00,-999.00,0.00,12.01,5.15,8.58,5.55,62.69,0.01,99.02,1.57,198.89,2.54,198.99
4,2001,1,1,4,0.00,-999.00,0.00,11.95,5.33,8.64,5.62,63.69,0.02,99.03,1.36,175.70,2.15,175.83
5,2001,1,1,5,0.00,-999.00,0.00,11.55,6.07,8.81,5.92,68.94,0.02,99.03,1.61,220.27,3.38,220.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177424,2021,3,29,16,267.67,0.58,0.62,40.86,-0.44,20.21,3.66,7.50,0.00,97.86,3.92,280.21,5.38,279.95
177443,2021,3,30,11,924.60,0.73,8.55,40.90,-0.63,20.14,3.66,7.38,0.00,97.93,8.85,278.17,10.94,278.08
177444,2021,3,30,12,919.25,0.73,8.33,41.94,-4.45,18.74,2.62,5.00,0.00,97.79,11.10,280.75,13.69,280.32
177445,2021,3,30,13,831.77,0.73,6.58,41.76,-6.33,17.72,2.20,4.25,0.00,97.67,12.09,285.28,14.89,284.71
177446,2021,3,30,14,666.58,0.68,4.10,40.69,-7.44,16.62,1.95,4.06,0.00,97.61,12.03,289.74,14.95,289.03

In [39]:
data['ALLSKY_KT'].apply(lambda x:pow(x,2))

0         998001.0
1         998001.0
2         998001.0
3         998001.0
4         998001.0
            ...
177475    998001.0
177476    998001.0
177477    998001.0
177478    998001.0
177479    998001.0
Name: ALLSKY_KT, Length: 177480, dtype: float64

In [49]:
data.drop(columns=['ALLSKY_SFC_UV_INDEX','CLRSKY_SFC_SW_DWN','ALLSKY_KT'])

,YEAR,MO,DY,HR,T2M,T2MDEW,T2MWET,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
0,2001,1,1,0,12.78,4.84,8.81,5.43,58.38,0.01,99.10,2.46,201.60,5.44,201.40
1,2001,1,1,1,12.35,4.96,8.65,5.49,60.50,0.01,99.06,2.23,208.45,4.44,208.37
2,2001,1,1,2,11.97,5.07,8.51,5.49,62.50,0.01,99.04,1.98,209.60,3.49,209.67
3,2001,1,1,3,12.01,5.15,8.58,5.55,62.69,0.01,99.02,1.57,198.89,2.54,198.99
4,2001,1,1,4,11.95,5.33,8.64,5.62,63.69,0.02,99.03,1.36,175.70,2.15,175.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177475,2021,3,31,19,27.34,-10.60,8.37,1.59,7.00,0.00,98.05,4.57,322.15,10.26,322.18
177476,2021,3,31,20,25.94,-10.74,7.59,1.59,7.50,0.00,98.10,4.46,323.83,10.00,323.86
177477,2021,3,31,21,24.52,-10.95,6.79,1.59,8.06,0.00,98.13,4.35,325.68,9.74,325.75
177478,2021,3,31,22,23.26,-11.30,5.98,1.53,8.44,0.00,98.14,4.38,326.71,9.72,326.81
177479,2021,3,31,23,22.14,-11.71,5.21,1.46,8.69,0.00,98.14,4.53,327.24,9.77,327.34